// This is a playground for testing generative code suggestion logging.

function fib(n) {
  if (n <= 1) {
    return n;
  }
  return fib(n - 1) + fib(n - 2;
}

console.log(fib(10));

// Expected output:

// This is hand-written:
console.log('hi');

// This is generated by the AI:
console.log(fib(10));

