// This is a playground for testing generative code suggestion logging.

// Here's a different change, also hand-written.

function fibonacci(n) {
  if (n < 2) {
    return n;
  } else {
    return fibonacci(n - 1) + fibonacci(n - 2);
  }
}

// This is hand-written:
function testFib() {
  let v = fibonacci(1);
  //console.log(v);
}

function sum(a, b) {
  return a + b;
}

// This is generated by the AI:
function testSum() {
  let v = sum(2, 3);
 // console.log(v);
}

let demoVar = "demo";
var demo2 = 123;

// here's some more ai-generated code:
function testDemo() {
  let v = demoVar + demo2;
  //console.log(v);
}

